### ISSUE TITLE
Problems in installation

### ISSUE THREAD

**Issue by gustavoDomingues** [justbuchanan/fontawesome-python#2]
Hello! When I try to run the "generate.py", this error appears:

File "C:/Users/RedWeltall/Desktop/fontawesome-python-master/fontawesome/generate.py", line 21, in main
    icons_list = yaml.load(requests.get(URI).text)['icons']
KeyError: 'icons'

Process finished with exit code 1

Do you know what happens?!

**Comment by justbuchanan** [comment]
It looks like fontawesome recently released version 5, which changed the structure of their github repo.

For now, I think the best option is to use their version 4 branch by passing "--revision fa-4" to the generate.py script. I'll need to take a deeper look at how version 5 works so I can update the script.

Thanks for letting me know!

**Comment by justbuchanan** [comment]
Closing in favor of #4
