### ISSUE TITLE
Merely prints font shortcode

### ISSUE THREAD

**Issue by Happy-Ferret** [justbuchanan/fontawesome-python#3]
Attempting to add ``fa.icons['thumbs-up']`` to a GTK3 label merely reveals the shortcode (i e ``\uf164``) on my machine.

I've installed and imported fontawesome-python, as well as the regular fontawesome font (``sudo apt-get install fonts-font-awesome``).

Any other step I need to take?

Adding ``font-family: FontAwesome;`` to the CSS of the GTK label didn't work, either.

**Comment by justbuchanan** [comment]
Hmm, it sounds to me like font awesome isn't being setup with gtk.

Check out this example: https://pythonexample.com/code/font-awesome/. They use the 'font_desc' attribute to select font awesome - have you tried that?
