### ISSUE TITLE
Upgrade to FontAwesome 5

### ISSUE THREAD

**Issue by vdimir** [justbuchanan/fontawesome-python#4]
Why it use 4 version? Is there some reason why it is not upgraded to 5 version except time? Some linux distr, e.g. arch version contain ttf-font-awesome 5 version

**Comment by justbuchanan** [comment]
Version 4 was the current version at the time I originally wrote this, but you're right that it should be updated to use version 5. Version 5 changed how the fontawesome project is structured, so it will take a little work to make that happen. I plan to get around to it eventually, but have been short on time lately. If this is something you're interested in, feel free to send a pull request :).

**Comment by justbuchanan** [comment]
I took a look at this and the update to fontawesome 5 wasn't too bad. I have a version of this working on the fa-5 branch of this repo: https://github.com/justbuchanan/fontawesome-python/tree/fa-5.

If you clone that branch and run:

~~~{.sh}
./fontawesome/generate.py --revision 5.3.1 > fontawesome/icons.py
python setup.py build
sudo python setup.py install
~~~

you'll have the latest fontawesome installed.

After some more testing, I'll get the new version uploaded to pypi.

**Comment by justbuchanan** [comment]
The new version is up: https://pypi.org/project/fontawesome/5.3.1.post1/.
